version: 2

sources:
  - name: default
    database: default  # Explicitly specify ClickHouse database
    tables:
      - name: auto_mpg___mpg_raw  # Must match EXACTLY (3 underscores)
        meta:
          database: default  # Optional but explicit